return {
    ["ass"] = "as{{AIeIXzVZx:s}}",
    ["beaner"] = "beane{{AIeIXzVZx:r}}", -- Unstable
    ["bitch"] = "bit{{AIeIXzVZx:ch}}",
    ["blowjob"] = "blow{{AIeIXzVZx:job}}",
    ["boob"] = "boo{{AIeIXzVZx:b}}",
    ["boner"] = "bon{{AIeIXzVZx:er}}", -- Unstable
    ["cock"] = "co{{AIeIXzVZx:ck}}",
    ["cunt"] = "cu{{AIeIXzVZx:nt}}",
    ["cum"] = "cu{{AIeIXzVZx:m}}",
    ["dick"] = "di{{zczxczvz:ck}}",
    ["dickhead"] = "di{{vzxzczxczvz:ck}}he{{AIeIXzVZx:ad}}", -- Fix
    ["dildo"] = "di{{AIeIXzVZx:ldo}}",
    ["dumb"] = "du{{AIeIXzVZx:mb}}", -- Unstable
    ["dumbass"] = "dumba{{AIeIXzVZx:ss}}", -- Unstable
    ["dyke"] = "dy{{AIeIXzVZx:ke}}",
    ["fag"] = "fa{{AIeIXzVZx:g}}",
    ["fuck"] = "fu{{AIeIXzVZx:ck}}",
    ["fucking"] = "fu{{AIeIXzVZx:ck}}in{{AIeIXzVZx:g}}", -- Fix
    ["gaylord"] = "gayl{{AIeIXzVZx:ord}}",
    ["hoe"] = "h{{zczxczvz:oe}}",
    ["jew"] = "je{{zczxczvz:w}}",
    ["jizz"] = "ji{{AIeIXzVZx:zz}}",
    ["kike"] = "ki{{AIeIXzVZx:ke}}",
    ["kkk"] = "k{{AIeIXzVZx:kk}}",
    ["kyke"] = "ky{{AIeIXzVZx:ke}}",
    ["masturbat"] = "mastur{{AIeIXzVZx:bat}}",
    ["motherfucker"] = "motherf{{zczxczvzaiei:ucker}}",
    ["motherfucking"] = "motherf{{zczxczvzaiei:uc}}kin{{AIeIXzVZx:g}}",
    ["nazi"] = "na{{AIeIXzVZx:zi}}",
    ["nigga"] = "ni{{AIeIXzVZx:gga}}",
    ["nigger"] = "ni{{AIeIXzVZx:gger}}",
    ["piss"] = "pi{{zczxczvz:ss}}",
    ["penis"] = "pe{{AIeIXzVZx:nis}}",
    ["pussy"] = "pu{{AIeIXzVZx:ssy}}",
    ["rap"] = "ra{{AIeIXzVZx:p}}",  -- Unstable
    ["retard"] = "reta{{AIeIXzVZx:rd}}",
    ["sex"] = "se{{AIeIXzVZx:x}}",
    ["shit"] = "sh{{AIeIXzVZx:it}}",
    ["slut"] = "sl{{zczxczvz:ut}}",
    ["sperm"] = "spe{{AIeIXzVZx:rm}}",
    ["stfu"] = "st{{AIeIXzVZx:fu}}",
    ["stupid"] = "stu{{AIeIXzVZx:pid}}",
    ["testicle"] = "test{{AIeIXzVZx:icle}}",
    ["tits"] = "ti{{AIeIXzVZx:ts}}",
    ["vagina"] = "va{{AIeIXzVZx:gi}}na", -- Unstable
    ["whore"] = "who{{AIeIXzVZx:re}}",
    -- MISC.
    ["discord"] = "disco{{zczxczvz:rd}}",
    ["kys"] = "k{{AIeIXzVZx:ys}}",
    ["kill"] = "ki{{zczxczvz:ll}}",
    ["wtf"] = "wt{{AIeIXzVZx:f}}",
    ["the"] = "th{{AIeIXzVZx:e}}",
    ["tho"] = "th{{AIeIXzVZx:o}}", -- Unstable
    ["lmao"] = "l{{AIeIXzVZx:mao}}",
    ["lmfao"] = "l{{AIeIXzVZx:mfao}}",
    ["suck"] = "suc{{AIeIXzVZx:k}}",
    ["nuts"] = "n{{AIeIXzVZx:uts}}", -- Unstable
    ["you"] = "y{{AIeIXzVZx:ou}}"
}
